# To create/run: kubectl apply -f nginx.pod.yaml --dry-run=client --validate=true
# To delete: kubectl delete -f nginx.pod.yaml
# To expose port: kubectl port-forward pod/nginx-pod 8080:80
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    rel: stable
spec:
  containers:
    - name: my-nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
