# To access management endpoint: kubectl port-forward pod/rabbitmq-deploy-0 8090:15672
# Then go to http://localhost:8090
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  # Headless service: service doesn't have an IP.
  # service's DNS entry returns IP addresses of each Pod in the StatefulSet
  # Each Pod also has its own DNS entry
  clusterIP: None
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      targetPort: 5672
      name: amqp