# source:  https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/
# Order of cmds: apply nginx.pv.yaml ==> nginx.pvc.yaml ==> nginx.deployment.yaml
# kubectl describe pod -l app=nginx-with-volume
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-with-volume
spec:
  selector:
    matchLabels:
      app: nginx-with-volume
  template:
    metadata:
      labels:
        app: nginx-with-volume
    spec:
      containers:
        - name: nginx-container
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            -  name: nginx-storage
               mountPath: "/usr/share/nginx/html"
      volumes:
        - name: nginx-storage
          persistentVolumeClaim:
            claimName: nginx-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-with-volume
spec:
  type: LoadBalancer
  selector:
    app: nginx-with-volume
  ports:
    - port: 8080
      targetPort: 80

