# To create/run: kubectl apply -f .
# To remove: kubectl delete -f .
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres-db
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db # must match spec.template.metadata.labels below
  template:
    metadata:
      labels:
        app: postgres-db # must match spec.selector.matchLabels above
    spec:
      containers:
        - name: db-container
          image: postgres:13
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - name: psql-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "psql -U postgres", "SELECT 1;"]
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: psql-data
          hostPath:
            path: /mnt/data/postgres # inside minikube
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service # hostname of db
spec:
  #type: LoadBalancer #uncomment to expose to localhost
  clusterIP: None
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 5432 # The port the Service listens on
      targetPort: 5432 # The port the traffic is sent to the Pod